CREATE TABLE Khoa(
	MaKhoa VARCHAR(5) PRIMARY KEY,
	TenKhoa VARCHAR(50) NOT null
);

CREATE TABLE Nganh(
	MaNganh VARCHAR(5) PRIMARY KEY,
	TenNganh VARCHAR(50) NOT NULL,
	Mota TEXT,
	MaKhoa VARCHAR(5) not NULL,
	FOREIGN KEY (MaKhoa) REFERENCES khoa(MaKhoa)
);

CREATE TABLE Lop(
	MaLop VARCHAR(5) PRIMARY KEY,
	TenLop VARCHAR(50) NOT NULL,
	MaNganh VARCHAR(5) not NULL,
	FOREIGN KEY (MaNganh) REFERENCES nganh(MaNganh)
);

CREATE TABLE sinhvien(
	MSSV VARCHAR(8) PRIMARY KEY,
	HoTen VARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT(1) NOT NULL,
	DiaChi TEXT NOT NULL,
	SDT CHAR(10),
	Email VARCHAR(100) NOT NULL,
	CCCD CHAR(12) NOT NULL,
	MaLop VARCHAR(5) NOT NULL,
	FOREIGN KEY(MaLop) REFERENCES lop(MaLop) 
);

CREATE TABLE giangvienhuongdan(
	MSGV VARCHAR(8) PRIMARY KEY,
	HoTen VARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT(1) NOT NULL,
	DiaChi TEXT NOT NULL,
	SDT CHAR(10),
	Email VARCHAR(100) NOT NULL,
	CCCD CHAR(12) NOT NULL,
	MaKhoa VARCHAR(5) NOT NULL,
	FOREIGN KEY(MaKhoa) REFERENCES Khoa(MaKhoa) 
);

CREATE TABLE KhoaHoc(
	MaKH VARCHAR(5) PRIMARY KEY,
	SoKhoa INT not null
);

CREATE TABLE donvithuctap(
	MaDVTT VARCHAR(8) PRIMARY KEY,
	TenDVTT VARCHAR(100) NOT NULL,
	DiaChi TEXT NOT NULL,
	SDT CHAR(10),
	Email VARCHAR(100) NOT NULL
);

CREATE TABLE canbohuongdan(
	MSCB VARCHAR(8) PRIMARY KEY,
	HoTen VARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT(1) NOT NULL,
	DiaChi TEXT NOT NULL,
	SDT CHAR(10),
	Email VARCHAR(100) NOT NULL,
	MaDVTT VARCHAR(8) NOT NULL,
	FOREIGN KEY(MaDVTT) REFERENCES donvithuctap(MaDVTT) 
);

CREATE TABLE Taikhoan(
	UserID VARCHAR(8) PRIMARY KEY,
	MatKhau VARCHAR(100) NOT NULL,
	UserRole CHAR(1)  NOT NULL
);

CREATE TABLE dotthuctap(
	STT MEDIUMINT PRIMARY KEY,
	NgayBatDau DATE NOT NULL,
	NgayKetThuc DATE NOT NULL,
	CHECK (NgayKetThuc > NgayBatDau ),
	MaKH VARCHAR(5),
	FOREIGN KEY(MaKH) REFERENCES khoahoc(MaKH)
);

CREATE TABLE tinhthanh(
	SoTinh TINYINT PRIMARY KEY,
	TenTinhThanh VARCHAR(30)
);

CREATE TABLE quanhuyen(
	SoTinh TINYINT NOT NULL,
	FOREIGN KEY(SoTinh) REFERENCES tinhthanh(SoTinh),
	TenQuanHuyen VARCHAR(30) NOT NULL 
);

CREATE TABLE detai(
	MaDeTai VARCHAR(10) PRIMARY KEY,
	MSSV VARCHAR(8) NOT null, 
	MSGV VARCHAR(8) NOT null, 
	MSCB VARCHAR(8) NOT null, 
	MaKH VARCHAR(5) NOT null, 
	STT MEDIUMINT NOT null, 
	TenDeTai VARCHAR(80) NOT null, 
	TieuDe VARCHAR(200), 
	TuKhoa VARCHAR(255), 
	NamThucHien DATE ,
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV),
	FOREIGN KEY(MSGV) REFERENCES giangvienhuongdan(MSGV),
	FOREIGN KEY(MSCB) REFERENCES canbohuongdan(MSCB),
	FOREIGN KEY(MaKH) REFERENCES khoahoc(MaKH),
	FOREIGN KEY(STT) REFERENCES dotthuctap(STT)
);

CREATE TABLE trinhdohocvan(
	IDHocVan VARCHAR(8) PRIMARY KEY ,
	TenHocVan VARCHAR(50) NOT NULL 
);

CREATE TABLE giaygioithieu(
	IDCV VARCHAR(8) PRIMARY KEY, 
	IDHocVan VARCHAR(8) NOT NULL,
	MaNganh VARCHAR(5) NOT NULL, 
	MSSV VARCHAR(8) NOT NULL,
	FOREIGN KEY(IDHocVan) REFERENCES trinhdohocvan(IDHocVan),
	FOREIGN KEY(MaNganh) REFERENCES nganh(MaNganh),
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV),
	KinhNghiem VARCHAR(255) NOT NULL, 
	ChungChi VARCHAR(255) NOT NULL, 
	KyNang VARCHAR(255) NOT NULL, 
	NgoaiNgu  VARCHAR(255) NOT NULL
	
);

CREATE TABLE noidungdanhgia(
	ID VARCHAR(10) PRIMARY KEY,
	NoiDung text
);

CREATE TABLE mucdochuongtrinhdaotao(
	IDMucDoCT VARCHAR(5) PRIMARY KEY,
	DanhGia text
);

CREATE TABLE PhieuDanhGiaKetQuaThucTap(
	MSPDGKQTT VARCHAR(8) PRIMARY KEY, 
	STT MEDIUMINT NOT NULL ,
	MSSV VARCHAR(8) NOT null, 
	MSCB VARCHAR(8) NOT null, 
	IDMucDoCT VARCHAR(5) NOT null, 
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV),
	FOREIGN KEY(MSCB) REFERENCES canbohuongdan(MSCB),
	FOREIGN KEY(STT) REFERENCES dotthuctap(STT),
	FOREIGN KEY(IDMucDoCT) REFERENCES mucdochuongtrinhdaotao(IDMucDoCT),
	NhanXet TEXT, 
	DongGop TEXT
);

CREATE TABLE ChiTietPhieuDanhGiaKetQuaThucTap(
	MSPDGKQTT VARCHAR(8) NOT NULL, 
	ID VARCHAR(10) NOT NULL,
	FOREIGN KEY(MSPDGKQTT) REFERENCES PhieuDanhGiaKetQuaThucTap(MSPDGKQTT),
	FOREIGN KEY(ID) REFERENCES noidungdanhgia(ID),
	Diem TINYINT 
);

CREATE TABLE CongViec(
	IDCongViec VARCHAR(8) PRIMARY KEY, 
	NoiDung text, 
	NhanXet text, 
	Buoi VARCHAR(20)
);

CREATE TABLE DieuKienCoSoThucTap(
	ID_DK VARCHAR(5) PRIMARY KEY, 
	VatChat VARCHAR(100) 
);

CREATE TABLE PhieuTiepNhanSinhVienThucTapThucTe(
	MSPXNTT VARCHAR(8) PRIMARY KEY, 
	MSSV VARCHAR(8) NOT null,
	STT MEDIUMINT NOT null,
	MSGV VARCHAR(8) NOT null,
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV), 
	FOREIGN KEY(STT) REFERENCES dotthuctap(STT),
	FOREIGN KEY(MSGV) REFERENCES giangvienhuongdan(MSGV)
);

CREATE TABLE ChiTietPhieuTiepNhanSinhVienThucTapThucTe(
	MSPXNTT VARCHAR(8) NOT NULL, 
	ID_DK VARCHAR(8) NOT null,
	FOREIGN KEY(MSPXNTT) REFERENCES PhieuTiepNhanSinhVienThucTapThucTe(MSPXNTT), 
	FOREIGN KEY(ID_DK) REFERENCES DieuKienCoSoThucTap(ID_DK)
);

CREATE TABLE PhieuTheoDoiSinhVienThucTap(
	MSPTDSV VARCHAR(8) PRIMARY KEY, 
	MSGV VARCHAR(8) NOT null, 
	MSCB VARCHAR(8) NOT null, 
	MSSV VARCHAR(8) NOT null, 
	STT MEDIUMINT NOT NULL ,
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV),
	FOREIGN KEY(MSCB) REFERENCES canbohuongdan(MSCB),
	FOREIGN KEY(STT) REFERENCES dotthuctap(STT),
	FOREIGN KEY(MSGV) REFERENCES giangvienhuongdan(MSGV)
);

CREATE TABLE PhieuGiaoViecSinhVienThucTap(
	MSPGVSV VARCHAR(8) PRIMARY KEY, 
	MSGV VARCHAR(8) NOT null, 
	MSCB VARCHAR(8) NOT null, 
	MSSV VARCHAR(8) NOT null, 
	STT MEDIUMINT NOT NULL ,
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV),
	FOREIGN KEY(MSCB) REFERENCES canbohuongdan(MSCB),
	FOREIGN KEY(STT) REFERENCES dotthuctap(STT),
	FOREIGN KEY(MSGV) REFERENCES giangvienhuongdan(MSGV)
);

CREATE TABLE ChiTietPhieuDanhGiaVaPhieuTheoDoi(
	MSPXNTT VARCHAR(8) NOT NULL,
	IDCongViec VARCHAR(8) NOT NULL,
	MSPGVSV VARCHAR(8) NOT NULL, 
	MSPTDSV VARCHAR(8) NOT NULL,
	FOREIGN KEY(MSPXNTT) REFERENCES PhieuTiepNhanSinhVienThucTapThucTe(MSPXNTT), 
	FOREIGN KEY(IDCongViec) REFERENCES CongViec(IDCongViec), 
	FOREIGN KEY(MSPGVSV) REFERENCES PhieuGiaoViecSinhVienThucTap(MSPGVSV),
	FOREIGN KEY(MSPTDSV) REFERENCES PhieuTheoDoiSinhVienThucTap(MSPTDSV),
	NgayBatDau DATE, 
	NgayKetThuc DATE,
	CHECK (NgayKetThuc > NgayBatDau), 
	NhanXet TEXT 
);

CREATE TABLE PhieuDanhGiaBaoCaoKetQua (
	MSPDGBCKQTT VARCHAR(8) PRIMARY KEY, 
	MSGV VARCHAR(8) NOT null, 
	MSSV VARCHAR(8) NOT null,
	FOREIGN KEY(MSSV) REFERENCES sinhvien(MSSV),
	FOREIGN KEY(MSGV) REFERENCES giangvienhuongdan(MSGV)
);

CREATE TABLE NoiDungBaoCao (
	Idndbc VARCHAR(8) PRIMARY KEY, 
	NoiDung TEXT NOT NULL, 
	DiemToiDa INT
);

CREATE TABLE ChiTietDanhGiaBaoCao (
	MSPDGBCKQTT VARCHAR(8) NOT  NULL, 
	IDndbc VARCHAR(8) NOT  NULL, 
	FOREIGN KEY(MSPDGBCKQTT) REFERENCES PhieuDanhGiaBaoCaoKetQua (MSPDGBCKQTT),
	FOREIGN KEY(IDndbc) REFERENCES NoiDungBaoCao (IDndbc),
	DiemSo int
);