//Thống kê

$('#ThongKe').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinThongKe').addClass("HienThiKhung");
    $('.ThongTinThongKe').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
$('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Sinh viên
$('#SinhVien').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinSinhVien').addClass("HienThiKhung");
    $('.ThongTinSinhVien').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Giáo viên
$('#GiaoVienHuongDan').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinGiaoVienHuongDan').addClass("HienThiKhung");
    $('.ThongTinGiaoVienHuongDan').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Đơn vị thực tập
$('#DonViThucTap').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinDonViThucTap').addClass("HienThiKhung");
    $('.ThongTinDonViThucTap').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Cán bộ hướng dẫn
$('#CanBoHuongDan').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinCanBoHuongDan').addClass("HienThiKhung");
    $('.ThongTinCanBoHuongDan').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//tài khoản
$('#TaiKhoan').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinTaiKhoan').addClass("HienThiKhung");
    $('.ThongTinTaiKhoan').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Điều hướng sinh viên
$('#DieuHuongSinhVienTT').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinDieuHuongSinhVien').addClass("HienThiKhung");
    $('.ThongTinDieuHuongSinhVien').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Bảng điểm số 
$('#BangDiemSo').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.BangDiemSoSinhVien').addClass("HienThiKhung");
    $('.BangDiemSoSinhVien').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Phiếu tiếp nhận sinh viên thực tập
$('#PXNSVTT').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinPhieuTiepNhan').addClass("HienThiKhung");
    $('.ThongTinPhieuTiepNhan').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Phiếu theo dõi sinh viên thực tập
$('#PTDSVTT').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinPhieuTheoDoi').addClass("HienThiKhung");
    $('.ThongTinPhieuTheoDoi').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Phiếu giao việc sinh viên thực tập
$('#PGVSVTT').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinPhieuGiaoViec').addClass("HienThiKhung");
    $('.ThongTinPhieuGiaoViec').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Phiếu đánh giá kết quả sinh viên thực tập
$('#PDGKQTT').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinPhieuDanhGiaKetQua').addClass("HienThiKhung");
    $('.ThongTinPhieuDanhGiaKetQua').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Phiếu đánh giá báo cáo kết quả sinh viên thực tập
$('#PDGBCKQTT').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass("HienThiKhung");
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.DSchoPheDuyetDonViThucTap').addClass('TatKhung');
    $('.DSchoPheDuyetDonViThucTap').removeClass('HienThiKhung');
});

//Danh sách chờ duyệt tài khoản đơn vị thực tập
$('#DuyetDonViThucTap').click(function (e) { 
    e.preventDefault();
    //Hiện
    $('.DSchoPheDuyetDonViThucTap').addClass("HienThiKhung");
    $('.DSchoPheDuyetDonViThucTap').removeClass("TatKhung");
        //Ẩn
    $('.ThongTinThongKe').addClass('TatKhung');
    $('.ThongTinThongKe').removeClass('HienThiKhung');
    $('.ThongTinSinhVien').addClass('TatKhung');
    $('.ThongTinSinhVien').removeClass('HienThiKhung');
    $('.ThongTinGiaoVienHuongDan').addClass('TatKhung');
    $('.ThongTinGiaoVienHuongDan').removeClass('HienThiKhung');
    $('.ThongTinDonViThucTap').addClass('TatKhung');
    $('.ThongTinDonViThucTap').removeClass('HienThiKhung');
    $('.ThongTinCanBoHuongDan').addClass('TatKhung');
    $('.ThongTinCanBoHuongDan').removeClass('HienThiKhung');
    $('.ThongTinTaiKhoan').addClass('TatKhung');
    $('.ThongTinTaiKhoan').removeClass('HienThiKhung');
    $('.BaoCaoDS_deTai').addClass('TatKhung');
    $('.BaoCaoDS_deTai').removeClass('HienThiKhung');
    $('.BaoCaoSVThucHienLai').addClass('TatKhung');
    $('.BaoCaoSVThucHienLai').removeClass('HienThiKhung');
    $('.BaoCaoDiemSoThucTap').addClass('TatKhung');
    $('.BaoCaoDiemSoThucTap').removeClass('HienThiKhung');
    $('.ThongTinDieuHuongSinhVien').addClass('TatKhung');
    $('.ThongTinDieuHuongSinhVien').removeClass('HienThiKhung');
    $('.BangDiemSoSinhVien').addClass('TatKhung');
    $('.BangDiemSoSinhVien').removeClass('HienThiKhung');
    $('.ThongTinPhieuTiepNhan').addClass('TatKhung');
    $('.ThongTinPhieuTiepNhan').removeClass('HienThiKhung');
    $('.ThongTinPhieuTheoDoi').addClass('TatKhung');
    $('.ThongTinPhieuTheoDoi').removeClass('HienThiKhung');
    $('.ThongTinPhieuGiaoViec').addClass('TatKhung');
    $('.ThongTinPhieuGiaoViec').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaKetQua').removeClass('HienThiKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').addClass('TatKhung');
    $('.ThongTinPhieuDanhGiaBaoCaoKetQua').removeClass('HienThiKhung');
});